// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// derivs_x_wr_t_Rcpp
double derivs_x_wr_t_Rcpp(const int GrowthCrvChoice, const int function_call, double x, double y, NumericVector params);
RcppExport SEXP _WAFishBiology_derivs_x_wr_t_Rcpp(SEXP GrowthCrvChoiceSEXP, SEXP function_callSEXP, SEXP xSEXP, SEXP ySEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type GrowthCrvChoice(GrowthCrvChoiceSEXP);
    Rcpp::traits::input_parameter< const int >::type function_call(function_callSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(derivs_x_wr_t_Rcpp(GrowthCrvChoice, function_call, x, y, params));
    return rcpp_result_gen;
END_RCPP
}
// RK4SYS_Rcpp
double RK4SYS_Rcpp(const int nstep, const int GrowthCrvChoice, const double h, double t, double x, NumericVector params);
RcppExport SEXP _WAFishBiology_RK4SYS_Rcpp(SEXP nstepSEXP, SEXP GrowthCrvChoiceSEXP, SEXP hSEXP, SEXP tSEXP, SEXP xSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type nstep(nstepSEXP);
    Rcpp::traits::input_parameter< const int >::type GrowthCrvChoice(GrowthCrvChoiceSEXP);
    Rcpp::traits::input_parameter< const double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(RK4SYS_Rcpp(nstep, GrowthCrvChoice, h, t, x, params));
    return rcpp_result_gen;
END_RCPP
}
// LenAtAge_Rcpp
double LenAtAge_Rcpp(const int j, NumericVector params, const int GrowthCrvChoice, const int nstep, const int CalculationStage, const double LenPrevIntAge, const double StartAge, NumericVector Obs_delta_t, NumericVector Obs_Initlen);
RcppExport SEXP _WAFishBiology_LenAtAge_Rcpp(SEXP jSEXP, SEXP paramsSEXP, SEXP GrowthCrvChoiceSEXP, SEXP nstepSEXP, SEXP CalculationStageSEXP, SEXP LenPrevIntAgeSEXP, SEXP StartAgeSEXP, SEXP Obs_delta_tSEXP, SEXP Obs_InitlenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type j(jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const int >::type GrowthCrvChoice(GrowthCrvChoiceSEXP);
    Rcpp::traits::input_parameter< const int >::type nstep(nstepSEXP);
    Rcpp::traits::input_parameter< const int >::type CalculationStage(CalculationStageSEXP);
    Rcpp::traits::input_parameter< const double >::type LenPrevIntAge(LenPrevIntAgeSEXP);
    Rcpp::traits::input_parameter< const double >::type StartAge(StartAgeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Obs_delta_t(Obs_delta_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Obs_Initlen(Obs_InitlenSEXP);
    rcpp_result_gen = Rcpp::wrap(LenAtAge_Rcpp(j, params, GrowthCrvChoice, nstep, CalculationStage, LenPrevIntAge, StartAge, Obs_delta_t, Obs_Initlen));
    return rcpp_result_gen;
END_RCPP
}
// TaggingGrowthModelNLLCalcs_Rcpp
NumericVector TaggingGrowthModelNLLCalcs_Rcpp(NumericVector params, const int nobs, const int GrowthCrvChoice, const int nstep, NumericVector Obs_delta_t, NumericVector Obs_Initlen);
RcppExport SEXP _WAFishBiology_TaggingGrowthModelNLLCalcs_Rcpp(SEXP paramsSEXP, SEXP nobsSEXP, SEXP GrowthCrvChoiceSEXP, SEXP nstepSEXP, SEXP Obs_delta_tSEXP, SEXP Obs_InitlenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const int >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< const int >::type GrowthCrvChoice(GrowthCrvChoiceSEXP);
    Rcpp::traits::input_parameter< const int >::type nstep(nstepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Obs_delta_t(Obs_delta_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Obs_Initlen(Obs_InitlenSEXP);
    rcpp_result_gen = Rcpp::wrap(TaggingGrowthModelNLLCalcs_Rcpp(params, nobs, GrowthCrvChoice, nstep, Obs_delta_t, Obs_Initlen));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WAFishBiology_derivs_x_wr_t_Rcpp", (DL_FUNC) &_WAFishBiology_derivs_x_wr_t_Rcpp, 5},
    {"_WAFishBiology_RK4SYS_Rcpp", (DL_FUNC) &_WAFishBiology_RK4SYS_Rcpp, 6},
    {"_WAFishBiology_LenAtAge_Rcpp", (DL_FUNC) &_WAFishBiology_LenAtAge_Rcpp, 9},
    {"_WAFishBiology_TaggingGrowthModelNLLCalcs_Rcpp", (DL_FUNC) &_WAFishBiology_TaggingGrowthModelNLLCalcs_Rcpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_WAFishBiology(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
